services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: stillswarm
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: jobapp
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres_net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_net
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  postgres_net:
    driver: bridge